dist: xenial
sudo: required
language: node_js
node_js:
  - 10

include:
  - os: linux
    dist: xenial
    before_install:
      - rm -rf node_modules

install:
  - npm install

script:
  - bash ./bin/test-contract-travis.sh