dist: xenial
sudo: required
language: node_js
node_js:
  - 10

include:
  - os: linux
    dist: xenial

install:
  - npm install
  - npm install -g ganache-cli@6.6.0
  - npm install -g truffle@5.0.38

script:
  - bash ./bin/test-contract-travis.sh